In [1]:
import numpy as np

In [2]:
np.random.seed(101)

x = np.random.randint(1, 1_000_000, 10).reshape(-1, 1)
y = np.random.randint(1, 1_000_000, 10).reshape(-1, 1)
z = np.random.randint(1, 1_000_000, 10).reshape(-1, 1)
zeros = np.zeros_like(x)

for i, j in zip(["x", "y", "z", "zeros"], [x, y, z, zeros]):
    print(f"Vector {i} =\n{j}\n")

Vector x =
[[176992]
 [214540]
 [476498]
 [204615]
 [661056]
 [311896]
 [579582]
 [471116]
 [937968]
 [753034]]

Vector y =
[[672718]
 [153129]
 [349829]
 [ 35392]
 [250793]
 [323318]
 [465213]
 [340701]
 [937071]
 [121862]]

Vector z =
[[348638]
 [915497]
 [ 32818]
 [456532]
 [864880]
 [615931]
 [649353]
 [315764]
 [755614]
 [871284]]

Vector zeros =
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]



# Commutativity

## Manual

In [3]:
def calc_vectors(vector_a, vector_b, calculation):
    if calculation == "sum":
        ans = [i + j for i, j in zip(vector_a.flatten(), vector_b.flatten())]
    elif calculation == "min":
        ans = [i - j for i, j in zip(vector_a.flatten(), vector_b.flatten())]
    return ans

In [4]:
sum_xy = calc_vectors(x, y, "sum")
sum_yx = calc_vectors(y, x, "sum")

sum_xy == sum_yx

True

## NumPy

In [5]:
np.array_equal(
    np.add(x, y),
    np.add(y, x)
)

True

# Associativity

In [6]:
sum_xy_z = calc_vectors(
    np.array(calc_vectors(x, y, "sum")),
    z,
    "sum"
)
sum_x_yz = calc_vectors(
    x,
    np.array(calc_vectors(y, z, "sum")),
    "sum"
)

sum_xy_z == sum_x_yz

True

## NumPy

In [7]:
np.array_equal(
    np.add(
        np.add(x, y),
        z
    ),
    np.add(
        x,
        np.add(y, z)
    ),
)

True

# Adding the Zero Has No Effect

## Manual

In [8]:
sum_x0 = calc_vectors(x, zeros, "sum")
sum_0x = calc_vectors(zeros, x, "sum")

sum_x0 == sum_0x == list(x.flatten())

True

## NumPy

In [9]:
np.array_equal(
    np.add(x, zeros),
    np.add(zeros, x)
)

True

# Substracting a Vector from Itself

## Manual

In [10]:
min_xx = calc_vectors(x, x, "min")

min_xx == list(zeros.flatten())

True

## NumPy

In [11]:
np.array_equal(
    np.subtract(x, x),
    zeros
)

True